name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up theos
        uses: beerpiss/theos-action@v1

      - name: Select Xcode version (14.0)
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.0.app
      
      - name: Build IPA
        run: |
          curl -sL https://github.com/permasigner/ldid/releases/latest/download/ldid_macosx_x86_64 -o ${{ github.workspace }}/ldid
          
          cd App
          xcodebuild build -scheme Santander -configuration "Release" CODE_SIGNING_ALLOWED="NO" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_IDENTITY="" BUILD_DIR=${{ github.workspace }}/xcodebuild
          cd ..

          cd Helper
          make clean
          make FINALPACKAGE=1

          cp .theos/obj/santanderhelper ${{ github.workspace }}/out/ipa/Payload/Santander.app/santanderhelper
          ldid -s -K${{ github.workspace }}/cert.p12 -Upassword ${{ github.workspace }}/out/ipa/Payload/Santander.app/santanderhelper

          mkdir -p ${{ github.workspace }}/out/ipa/Payload
          cp -R ${{ github.workspace }}/xcodebuild/Release-iphoneos/Santander.app out/ipa/Payload
          ldid -S${{ github.workspace }}/App/entitlements.plist ${{ github.workspace }}/out/ipa/Payload/Santander.app
          cd ${{ github.workspace }}/out/ipa
          zip -r ${{ github.workspace }}/Santander.ipa .
          rm -rf ${{ github.workspace }}/out/ipa xcodebuild

      - name: Upload IPA
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Santander
          path: ${{ github.workspace }}/Santander.ipa
