name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Select Xcode version (14.0)
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.0.app
      
      - name: Build IPA
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload IPA
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Santander
          path: out/Santander.ipa
